#Workflow
name: CI Demo
#workflow trigger
on: [push, pull_request, workflow_dispatch]
#Jobs definition
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate unit tests
        run: echo "All tests passed!"

      - name: Simulate build step
        run: echo "Application built successfully"

      - name: Final success message
        run: echo "CI pipeline completed!"
